version: '2'
services:
  cassandra:
    image: cassandra:2.1
    container_name: cassandra
    environment:
      CASSANDRA_BROADCAST_ADDRESS: "cassandra"
    ports:
      - '9042:9042'
    volumes:
      - "/openblockchain/cassandra/data:/var/lib/cassandra"
    restart: always
  bitcoin:
    image: 'aluxian/bitcoin:latest'
    command: 'bitcoin /usr/bin/bitcoind -conf=/etc/bitcoin.conf -txindex'
    container_name: bitcoin
    environment:
      - CONF_RPCALLOWIP=0.0.0.0/0
      - CONF_RPCPASSWORD=pass123
      - CONF_RPCUSER=bitcoinrpc
      - CONF_SERVER=1
    expose:
      - '8332'
    volumes:
      - '/openblockchain/bitcoin/data:/bitcoin/data'
  scanner:
    build: .
    command: 'sbt "run-main org.dyne.danielsan.openblockchain.Driver 0"'
    environment:
      - 'BITCOIN_AUTH=bitcoinrpc:pass123'
      - 'BITCOIN_SERVER_URL=http://bitcoin:8332'
      - 'BITCOIN_DBCACHE=512'
      - 'BITCOIN_RPCTHREADS=8'
      - 'CASSANDRA_HOST=cassandra'
    depends_on:
      - bitcoin
      - cassandra
    volumes:
      - '/openblockchain/scanner/.ivy2:/root/.ivy2'
networks:
  default:
    external:
      name: opbnet
