version: '2'
services:
  cassandra:
    image: cassandra:2.1
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=cassandra
    volumes:
      - /openblockchain/cassandra/data:/var/lib/cassandra
    restart: on-failure
  bitcoin:
    image: 'aluxian/bitcoin:latest'
    command: 'root /usr/bin/bitcoind -conf=/etc/bitcoin.conf -txindex'
    environment:
      - CONF_RPCALLOWIP=0.0.0.0/0
      - CONF_RPCPASSWORD=pass123
      - CONF_RPCUSER=bitcoinrpc
      - CONF_SERVER=1
    volumes:
      - /openblockchain/bitcoin/data:/bitcoin/data
    restart: on-failure
  scanner:
    build: .
    command: 'sbt "run-main org.dyne.danielsan.openblockchain.Driver --scale=1"'
    environment:
      - BITCOIN_AUTH=bitcoinrpc:pass123
      - BITCOIN_SERVER_URL=http://bitcoin:8332
      - BITCOIN_DBCACHE=1024
      - BITCOIN_RPCTHREADS=8
      - CASSANDRA_HOST=cassandra
    links:
      - bitcoin
      - cassandra
    volumes:
      - /openblockchain/scanner/.ivy2:/root/.ivy2
    restart: on-failure
networks:
  default:
    external:
      name: opbnet
